import { useEffect, useState } from 'react'
import QRCode from 'qrcode'

const RELAY_BASE_URL = import.meta.env.VITE_RELAY_BASE_URL

type Props = {
  deviceId: string
  size?: number
  baseUrl?: string
}

export function getDeviceQrUrl(deviceId: string, baseUrl?: string): string {
  const base = (baseUrl || RELAY_BASE_URL || '').trim()
  if (!base) {
    return `/device/${deviceId}`
  }
  let trimmedBase = base.replace(/\/+$/, '')
  if (!trimmedBase.endsWith('/device')) {
    trimmedBase = `${trimmedBase}/device`
  }
  return `${trimmedBase}/${deviceId}`
}

export function QRPreview({ deviceId, size = 96, baseUrl }: Props) {
  const [svg, setSvg] = useState('')
  const url = getDeviceQrUrl(deviceId, baseUrl)

  useEffect(() => {
    QRCode.toString(url, {
      type: 'svg',
      errorCorrectionLevel: 'M',
      margin: 4,
      width: size,
    }).then(setSvg)
  }, [url, size])

  return (
    <div
      aria-label={`QR dla urządzenia ${deviceId}`}
      className="bg-white rounded p-1 shrink-0"
      // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG is generated by the qrcode library from a URL, not user input
      dangerouslySetInnerHTML={{ __html: svg }}
      role="img"
      style={{ width: size, height: size }}
    />
  )
}

export async function exportDeviceQrAsPng(deviceUuid: string) {
  const url = getDeviceQrUrl(deviceUuid)
  const dataUrl = await QRCode.toDataURL(url, {
    errorCorrectionLevel: 'M',
    margin: 4,
    width: 1024,
  })
  return window.qrAPI.savePng(dataUrl, `relay-${deviceUuid.slice(0, 8)}.png`)
}

